[http]

  [http.routers]
      
    [http.routers.wmsortho]
      entryPoints = ["websecure"]
      rule = "Host(`localhost`) && PathPrefix(`/wms`)"
      service = "wmsortho"
      #tls = false

    [http.services]
      [http.services.wmsortho]
        [http.services.wmsortho.loadBalancer]
          [[http.services.wmsortho.loadBalancer.servers]]
            url = "https://geo.weather.gc.ca/geomet/"
            #url = "https://geo.weather.gc.ca/geomet/?lang=en&service=WMS&request=GetCapabilities"
